data_prep:
  version: "1.0"
  dataset_name: "iris"
  feature_columns: ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]
  target_column: "Species"
  id_column: "Id"

feature_prep:
  apply_scaling: true
  scaling_method: "standard"

model_evaluation:
  split_ratio: 0.2
  cv_folds: 5
  random_state: 42
  evaluation_metric: "macro_auc"
  stratify: true

model:
  model_type: "svm"
  model_params:
    kernel: "rbf"
    random_state: 42
    probability: true
  random_state: 42



