data_prep:
  version: "1.0"
  dataset_name: "iris"
  feature_columns: ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]
  target_column: "Species"
  id_column: "Id"

feature_prep:
  apply_scaling: true
  scaling_method: "standard"

model_evaluation:
  split_ratio: 0.2
  cv_folds: 5
  random_state: 42
  evaluation_metric: "macro_auc"
  stratify: true

# Multi-algorithm experiment configuration
algorithms:
  svm_linear:
    model_type: "svm"
    base_params:
      kernel: "linear"
      probability: true
      random_state: 42
    hyperparameter_grid:
      C: [0.1, 1, 10, 100]
  
  svm_rbf:
    model_type: "svm"
    base_params:
      kernel: "rbf"
      probability: true
      random_state: 42
    hyperparameter_grid:
      C: [0.1, 1, 10]
      gamma: ["scale", 0.001, 0.01, 0.1]
  
  logistic_regression:
    model_type: "logistic_regression"
    base_params:
      random_state: 42
      max_iter: 1000
      multi_class: "ovr"
    hyperparameter_grid:
      C: [0.01, 0.1, 1, 10]
      solver: ["liblinear", "lbfgs"]
  
  random_forest:
    model_type: "random_forest"
    base_params:
      random_state: 42
    hyperparameter_grid:
      n_estimators: [50, 100, 200]
      max_depth: [3, 5, null]
      min_samples_split: [2, 5]

hyperparameter_optimization:
  method: "GridSearchCV"
  scoring: "roc_auc_ovr"
  cv_folds: 3
  n_jobs: -1

# Backward compatibility - default to SVM RBF for single model usage
model:
  model_type: "svm"
  model_params:
    kernel: "rbf"
    random_state: 42
    probability: true
  random_state: 42



